<?xml version="1.0" encoding="utf-8"?><testsuites><testsuite name="pytest" errors="0" failures="2" skipped="0" tests="8" time="81.695" timestamp="2025-08-30T13:26:10.975723" hostname="dut7358"><testcase classname="test.distributed.checkpoint.test_checkpoint.TestDistributedCheckpointing" name="test_default_metadata" time="15.648" /><testcase classname="test.distributed.checkpoint.test_checkpoint.TestDistributedCheckpointing" name="test_tensor_metadata_with_missing_rank_spec" time="15.226" /><testcase classname="test.distributed.checkpoint.test_checkpoint.TestDistributedFailure" name="test_dummy_reader_works" time="3.910"><failure message="AssertionError: Scalars are not equal!&#10;&#10;Expected 0 but got -6.&#10;Absolute difference: 6&#10;Relative difference: inf&#10;Expected exit code 0 but got -6 for pid: 2480980">Traceback (most recent call last):
  File "/tmp/xpu-tool/Python/3.10.18/x64/lib/python3.10/site-packages/torch/testing/_internal/common_distributed.py", line 716, in wrapper
    self._join_processes(fn)
  File "/tmp/xpu-tool/Python/3.10.18/x64/lib/python3.10/site-packages/torch/testing/_internal/common_distributed.py", line 980, in _join_processes
    self._check_return_codes(fn, elapsed_time)
  File "/tmp/xpu-tool/Python/3.10.18/x64/lib/python3.10/site-packages/torch/testing/_internal/common_distributed.py", line 1056, in _check_return_codes
    self.assertEqual(
  File "/tmp/xpu-tool/Python/3.10.18/x64/lib/python3.10/site-packages/torch/testing/_internal/common_utils.py", line 4181, in assertEqual
    raise error_metas.pop()[0].to_error(  # type: ignore[index]
AssertionError: Scalars are not equal!

Expected 0 but got -6.
Absolute difference: 6
Relative difference: inf
Expected exit code 0 but got -6 for pid: 2480980</failure></testcase><testcase classname="test.distributed.checkpoint.test_checkpoint.TestDistributedFailure" name="test_dummy_writer_works" time="16.331" /><testcase classname="test.distributed.checkpoint.test_checkpoint.TestDistributedFailure" name="test_load_error_handling" time="3.911"><failure message="AssertionError: Scalars are not equal!&#10;&#10;Expected 0 but got -6.&#10;Absolute difference: 6&#10;Relative difference: inf&#10;Expected exit code 0 but got -6 for pid: 2481584">Traceback (most recent call last):
  File "/tmp/xpu-tool/Python/3.10.18/x64/lib/python3.10/site-packages/torch/testing/_internal/common_distributed.py", line 716, in wrapper
    self._join_processes(fn)
  File "/tmp/xpu-tool/Python/3.10.18/x64/lib/python3.10/site-packages/torch/testing/_internal/common_distributed.py", line 980, in _join_processes
    self._check_return_codes(fn, elapsed_time)
  File "/tmp/xpu-tool/Python/3.10.18/x64/lib/python3.10/site-packages/torch/testing/_internal/common_distributed.py", line 1056, in _check_return_codes
    self.assertEqual(
  File "/tmp/xpu-tool/Python/3.10.18/x64/lib/python3.10/site-packages/torch/testing/_internal/common_utils.py", line 4181, in assertEqual
    raise error_metas.pop()[0].to_error(  # type: ignore[index]
AssertionError: Scalars are not equal!

Expected 0 but got -6.
Absolute difference: 6
Relative difference: inf
Expected exit code 0 but got -6 for pid: 2481584</failure></testcase><testcase classname="test.distributed.checkpoint.test_checkpoint.TestDistributedFailure" name="test_load_error_handling_no_dist" time="3.509" /><testcase classname="test.distributed.checkpoint.test_checkpoint.TestDistributedFailure" name="test_save_error_handling" time="17.032" /><testcase classname="test.distributed.checkpoint.test_checkpoint.TestDistributedFailure" name="test_save_error_handling_no_dist" time="3.810" /></testsuite></testsuites>