<?xml version="1.0" encoding="utf-8"?><testsuites><testsuite name="pytest" errors="0" failures="1" skipped="0" tests="16" time="369.672" timestamp="2025-08-22T15:55:53.274119" hostname="dut7358"><testcase classname="test.distributed.checkpoint.test_utils.TestMedatadaIndex" name="test_dcp_logger" time="0.199" /><testcase classname="test.distributed.checkpoint.test_utils.TestMedatadaIndex" name="test_flat_data" time="0.004" /><testcase classname="test.distributed.checkpoint.test_utils.TestMedatadaIndex" name="test_index_hint_ignored_on_equals" time="0.001" /><testcase classname="test.distributed.checkpoint.test_utils.TestMedatadaIndex" name="test_index_hint_ignored_on_hash" time="0.001" /><testcase classname="test.distributed.checkpoint.test_utils.TestMedatadaIndex" name="test_init_convert_offset" time="0.001" /><testcase classname="test.distributed.checkpoint.test_utils.TestMedatadaIndex" name="test_sharded_tensor_lookup" time="0.002" /><testcase classname="test.distributed.checkpoint.test_utils.TestReaderView" name="testAllRead" time="0.001" /><testcase classname="test.distributed.checkpoint.test_utils.TestReaderView" name="testLongRead" time="0.001" /><testcase classname="test.distributed.checkpoint.test_utils.TestReaderView" name="testLongReadinto" time="0.001" /><testcase classname="test.distributed.checkpoint.test_utils.TestReaderView" name="testShortRead" time="0.000" /><testcase classname="test.distributed.checkpoint.test_utils.TestReaderView" name="testShortReadinto" time="0.001" /><testcase classname="test.distributed.checkpoint.test_utils.TestDistWrapper" name="test_barrier" time="300.018"><failure message="RuntimeError: Process 0 terminated or timed out after 300.01091861724854 seconds">Traceback (most recent call last):
  File "/home/jenkins/.conda/envs/xpu_op_/lib/python3.10/site-packages/torch/testing/_internal/common_distributed.py", line 716, in wrapper
    self._join_processes(fn)
  File "/home/jenkins/.conda/envs/xpu_op_/lib/python3.10/site-packages/torch/testing/_internal/common_distributed.py", line 980, in _join_processes
    self._check_return_codes(fn, elapsed_time)
  File "/home/jenkins/.conda/envs/xpu_op_/lib/python3.10/site-packages/torch/testing/_internal/common_distributed.py", line 1025, in _check_return_codes
    raise RuntimeError(
RuntimeError: Process 0 terminated or timed out after 300.01091861724854 seconds</failure></testcase><testcase classname="test.distributed.checkpoint.test_utils.TestDistWrapper" name="test_broadcast_object_global_local_mismatch" time="17.033" /><testcase classname="test.distributed.checkpoint.test_utils.TestDistWrapper" name="test_broadcast_object_with_nonzero_coordinator" time="16.035" /><testcase classname="test.distributed.checkpoint.test_utils.TestDistWrapper" name="test_gather_object" time="17.032" /><testcase classname="test.distributed.checkpoint.test_utils.TestDistWrapper" name="test_scatter_object" time="16.749" /></testsuite></testsuites>